// ─────────────────────────────────────────────────────────────
// TutorCanvas Core — DSL Type Definitions
// Canonical types from spec.md. This is the single source of truth.
// ─────────────────────────────────────────────────────────────

// ── TutorAction Union ──────────────────────────────────────

export type TutorAction =
  | CreateBlockAction
  | DrawDiagramAction
  | HighlightAction;

export type Action = TutorAction | CustomAction;

// ── Custom Action (for extensibility) ───────────────────────
export interface CustomAction {
  type: 'custom';
  /** Stable ID for referencing this node later */
  ref?: string;
  /** Key into renderer registry */
  renderer: string;
  /** Arbitrary payload owned by the custom renderer */
  data: unknown;
  /** Where to place it on the canvas */
  position: SemanticPosition;
  /** Size preset or explicit dimensions */
  size?: CustomSize;
  /** Optional color role for consistent theming */
  color?: ColorRole;
  /** Narration that plays while this node animates */
  speech?: string;
  /** When this action starts, in seconds relative to audio start */
  start?: number;
  /** How long the reveal animation runs, in seconds */
  duration?: number;
  /** Absolute start offset in segment timeline (ms) — prefer `start` (seconds) */
  atMs?: number;
  /** Explicit reveal duration for this action (ms) — prefer `duration` (seconds) */
  durationMs?: number;
  /** Sync behavior for this action */
  sync?: SyncSpec;
  /** Reveal behavior for this action */
  reveal?: RevealSpec;
  /** Sticky nodes persist across section() calls */
  sticky?: boolean;
}

export type CustomSize =
  | SizeVariant
  | {
      width: number;
      height: number;
    };

// ── Block Action ───────────────────────────────────────────

export interface CreateBlockAction {
  type: 'create_block';
  /** Unique stable ID the AI can reference later. Generated by frontend if not provided. */
  ref?: string;
  /** What kind of content to render */
  block_type: BlockType;
  /** The actual content — plain text, markdown, or LaTeX string */
  content: string;
  /** Where to place it on the canvas */
  position: SemanticPosition;
  /** Size variant — controls the fixed width contract */
  size?: SizeVariant;
  /** Color role — maps to palette internally */
  color?: ColorRole;
  /** Narration that plays while this block animates in */
  speech?: string;
  /** When this action starts, in seconds relative to audio start */
  start?: number;
  /** How long the reveal animation runs, in seconds */
  duration?: number;
  /** Absolute start offset in segment timeline (ms) — prefer `start` (seconds) */
  atMs?: number;
  /** Explicit reveal duration for this action (ms) — prefer `duration` (seconds) */
  durationMs?: number;
  /** Sync behavior for this action */
  sync?: SyncSpec;
  /** Reveal behavior for this action */
  reveal?: RevealSpec;
  /** If true, this block persists across section() calls */
  sticky?: boolean;
  /** Optional subtitle for title blocks */
  subtitle?: string;
  /** For bullet_list: array of items */
  items?: string[];
}

export type BlockType =
  | 'title'
  | 'body'
  | 'theorem'
  | 'formula'
  | 'bullet_list'
  | 'note'
  | 'definition'
  | 'code';

export type SizeVariant = 'small' | 'medium' | 'large';
export type ColorRole = 'primary' | 'accent' | 'highlight' | 'danger';

// ── Diagram Action ─────────────────────────────────────────

export interface DrawDiagramAction {
  type: 'draw_diagram';
  ref?: string;
  /** What kind of diagram to draw */
  diagram_type: DiagramType;
  /** Diagram-specific data schema */
  data: DiagramData;
  position: SemanticPosition;
  speech?: string;
  /** When this action starts, in seconds relative to audio start */
  start?: number;
  /** How long the reveal animation runs, in seconds */
  duration?: number;
  /** Absolute start offset in segment timeline (ms) — prefer `start` (seconds) */
  atMs?: number;
  /** Explicit reveal duration for this action (ms) — prefer `duration` (seconds) */
  durationMs?: number;
  /** Sync behavior for this action */
  sync?: SyncSpec;
  /** Reveal behavior for this action */
  reveal?: RevealSpec;
  /** Caption below the diagram */
  caption?: string;
  color?: ColorRole;
  sticky?: boolean;
}

export type DiagramType =
  | 'cartesian'
  | 'geometry'
  | 'flowchart'
  | 'venn'
  | 'bar_chart'
  | 'pie_chart';

// ── Highlight Action ───────────────────────────────────────

export interface HighlightAction {
  type: 'highlight';
  /** Shape ref to highlight */
  target: string;
  /** How to highlight it */
  style?: HighlightStyle;
  /** Color of the highlight ring */
  color?: 'accent' | 'highlight' | 'danger';
  /** Narration that plays while highlight animates */
  speech?: string;
  /** When this action starts, in seconds relative to audio start */
  start?: number;
  /** How long the reveal animation runs, in seconds */
  duration?: number;
  /** Absolute start offset in segment timeline (ms) — prefer `start` (seconds) */
  atMs?: number;
  /** Explicit reveal duration for this action (ms) — prefer `duration` (seconds) */
  durationMs?: number;
  /** Sync behavior for this action */
  sync?: SyncSpec;
  /** Reveal behavior for this action */
  reveal?: RevealSpec;
}

export type HighlightStyle = 'circle' | 'box' | 'underline' | 'arrow';

// ── Semantic Position ──────────────────────────────────────

/**
 * The AI never provides pixel coordinates.
 * It uses these semantic positions.
 * The layout engine resolves them to {x, y}.
 */
export type SemanticPosition =
  | 'center'
  | 'top-left'
  | 'top-right'
  | 'top-center'
  | 'bottom-left'
  | 'bottom-right'
  | 'bottom-center'
  | `below:${string}`
  | `above:${string}`
  | `beside:${string}`
  | `left-of:${string}`
  | `right-of:${string}`;

// ── Diagram Data — Union ───────────────────────────────────

export type DiagramData =
  | CartesianData
  | GeometryData
  | FlowchartData
  | VennData
  | BarChartData
  | PieChartData;

export interface CartesianData {
  type: 'cartesian';
  domain: [number, number];
  range: [number, number];
  x_label?: string;
  y_label?: string;
  functions: {
    expression: string;
    label?: string;
    color?: string;
  }[];
  points?: { x: number; y: number; label?: string }[];
}

export interface GeometryData {
  type: 'geometry';
  shapes: GeometryShape[];
}

export type GeometryShape =
  | { type: 'circle'; cx: number; cy: number; r: number; label?: string }
  | { type: 'line'; x1: number; y1: number; x2: number; y2: number; label?: string }
  | { type: 'polygon'; points: [number, number][]; label?: string }
  | { type: 'angle'; vertex: [number, number]; from: [number, number]; to: [number, number]; label?: string }
  | { type: 'triangle'; a: [number, number]; b: [number, number]; c: [number, number]; labels?: { a?: string; b?: string; c?: string } }
  | { type: 'rectangle'; x: number; y: number; w: number; h: number; label?: string };

export interface FlowchartData {
  type: 'flowchart';
  nodes: { id: string; text: string; shape?: 'rect' | 'diamond' | 'pill' }[];
  edges: { from: string; to: string; label?: string }[];
}

export interface VennData {
  type: 'venn';
  sets: { label: string; items: string[] }[];
  intersection?: string[];
}

export interface BarChartData {
  type: 'bar_chart';
  bars: { label: string; value: number; color?: string }[];
  y_label?: string;
}

export interface PieChartData {
  type: 'pie_chart';
  slices: { label: string; value: number; color?: string }[];
}

// ── Animation Plan ─────────────────────────────────────────

export type EntranceType = 'stroke' | 'char-reveal' | 'fade' | 'token-reveal';

export interface AnimationPlan {
  /** How the node enters the canvas */
  entrance: EntranceType;
  /** Duration in ms for the entrance animation */
  duration: number;
  /** Delay before animation starts (ms) — used for audio sync */
  delay: number;
  /** If this action has speech, the audio duration estimate */
  speech_duration?: number;
  /** Reveal behavior metadata for renderers */
  reveal?: RevealSpec;
}

// ── Sync & Reveal Contracts ────────────────────────────────

export type SyncMode = 'audioLocked' | 'durationLocked' | 'manual';

export interface SyncSpec {
  mode?: SyncMode;
}

export type RevealMode = 'sequential' | 'parallel' | 'stagger' | 'manual' | 'audio';

export interface RevealMarker {
  name: string;
  /** 0..1 position in reveal progress */
  at: number;
}

export interface RevealSpec {
  mode?: RevealMode;
  /** Number of logical steps for progressive reveal */
  steps?: number;
  /** Stagger delay (ms) for stagger mode */
  staggerMs?: number;
  /** Named reveal milestones */
  markers?: RevealMarker[];
}

// ── Audio Progress ─────────────────────────────────────────

export interface AudioProgress {
  /** Current playback position in ms */
  currentTimeMs: number;
  /** Total audio duration in ms */
  durationMs: number;
  /** Normalized progress 0..1 */
  progress: number;
}

// ── Resolved Node ──────────────────────────────────────────

/**
 * What the layout engine outputs.
 * This is what the Node Factory receives.
 */
export interface ResolvedNode {
  /** Stable ID */
  id: string;
  /** React Flow node type — maps to a component */
  node_type: NodeType;
  /** Final canvas coordinates */
  x: number;
  y: number;
  /** Fixed dimensions from size contract */
  width: number;
  height: number;
  /** Content payload */
  content: BlockContent | DiagramContent | HighlightContent | CustomContent;
  /** How to animate it in */
  animation: AnimationPlan;
  /** Visual properties */
  color: string;
  sticky: boolean;
  /** Reference to the original action for debugging */
  action_ref?: string;
}

export type NodeType = 'text' | 'formula' | 'diagram' | 'note' | 'highlight' | 'custom';

// ── Content Payloads ───────────────────────────────────────

export interface BlockContent {
  type: 'block';
  block_type: BlockType;
  content: string;
  subtitle?: string;
  items?: string[];
}

export interface DiagramContent {
  type: 'diagram';
  diagram_type: DiagramType;
  data: DiagramData;
  caption?: string;
}

export interface HighlightContent {
  type: 'highlight';
  target: string;
  style: HighlightStyle;
  color: string;
}

export interface CustomContent {
  type: 'custom';
  renderer: string;
  data: unknown;
}

// ── Collision Detection ────────────────────────────────────

export interface AABB {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

export interface CollisionEntry {
  id: string;
  bounds: AABB;
  sticky: boolean;
}

// ── Layout Engine I/O ──────────────────────────────────────

export interface Cursor {
  x: number;
  y: number;
}
